### ISSUE TITLE
task1 numpy_based.py scipy.sparse.csr.csr_matrix to np.ndarray

### ISSUE THREAD

**Issue by dearchill** [Stark-JC/code-for-nlp-beginner#1]
numpy_based.py line58 返回的是用scipy的csr_matrix保存的稀疏矩阵，没有转为np.ndarray，导致line106判断为False然后产生mini-batch时出错，所以line152传入参数不是mini-batch导致这里用的是BGD而不是MBGD

**Comment by jiacheng-ye** [comment]
谢谢指正，已改
